import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { updatePhase } from "../../actions";

export default async function PhasePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; error?: string }> }) {
  const { id } = await params; const { saved, error } = await searchParams; const supabase = await createClient(); const { data: identity } = await supabase.auth.getClaims(); if (!identity?.claims.sub) redirect("/login");
  const { data: phase } = await supabase.from("phases").select("*").eq("id", id).maybeSingle(); if (!phase) notFound();
  return <main className="app-shell"><header className="topbar"><h1>Edit phase</h1><Link href="/setup">Setup</Link></header>{saved && <p className="notice">Phase saved.</p>}{error && <p className="error">{error}</p>}<form action={updatePhase} className="section measurement-form"><input type="hidden" name="id" value={id} /><label>Name<input name="name" required defaultValue={phase.name} /></label><div className="measurement-grid"><label>Start<input name="start_date" type="date" required defaultValue={phase.start_date} /></label><label>End / close<input name="end_date" type="date" defaultValue={phase.end_date ?? ""} /></label></div><div className="measurement-grid"><label>Nutrition<select name="nutrition_goal" defaultValue={phase.nutrition_goal}><option value="gain">Gain</option><option value="fat_loss">Fat loss</option><option value="mini_cut">Mini cut</option><option value="maintenance">Maintenance</option><option value="custom">Custom</option></select></label><label>Training<select name="training_goal" defaultValue={phase.training_goal}><option value="hypertrophy">Hypertrophy</option><option value="strength">Strength</option><option value="maintain">Maintain</option><option value="general">General</option><option value="custom">Custom</option></select></label></div><div className="measurement-grid"><label>Target kcal<input name="target_calories_kcal" type="number" defaultValue={phase.target_calories_kcal ?? ""} /></label><label>Maintenance kcal<input name="estimated_maintenance_kcal" type="number" defaultValue={phase.estimated_maintenance_kcal ?? ""} /></label><label>Rate kg/week<input name="target_rate_kg_per_week" type="number" step="0.01" defaultValue={phase.target_rate_kg_per_week ?? ""} /></label></div><label>Notes<textarea name="notes" rows={3} defaultValue={phase.notes ?? ""} /></label><button className="primary">Save phase</button></form></main>;
}
