import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createSetupItem } from "./actions";

function Form({ kind, children }: { kind: string; children: React.ReactNode }) { return <form action={createSetupItem} className="setup-form"><input type="hidden" name="kind" value={kind} />{children}<button className="primary">Add</button></form>; }
export default async function SetupPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const supabase = await createClient(); const { data: auth } = await supabase.auth.getClaims(); if (!auth?.claims.sub) redirect("/login");
  const [{ data: phases }, { data: programs }, { data: exercises }, { data: templates }] = await Promise.all([supabase.from("phases").select("*").order("start_date", { ascending: false }), supabase.from("programs").select("*").order("start_date", { ascending: false }), supabase.from("exercises").select("*").eq("archived", false).order("name"), supabase.from("workout_templates").select("*,programs(name)").eq("archived", false).order("position")]);
  const { saved, error } = await searchParams; const today = new Date().toISOString().slice(0, 10);
  return <main className="app-shell"><header className="topbar"><div><p className="eyebrow">Setup</p><h1>Training plan</h1></div><Link href="/">Today</Link></header>{saved && <p className="notice">Saved.</p>}{error && <p className="error">{error}</p>}<section className="section"><h2>Phase</h2><Form kind="phase"><label>Name<input name="name" required placeholder="Lean gain" /></label><label>Start<input name="start_date" type="date" required defaultValue={today} /></label><label>Nutrition goal<select name="nutrition_goal"><option value="gain">Gain</option><option value="fat_loss">Fat loss</option><option value="maintenance">Maintenance</option><option value="mini_cut">Mini cut</option><option value="custom">Custom</option></select></label><label>Training goal<select name="training_goal"><option value="hypertrophy">Hypertrophy</option><option value="strength">Strength</option><option value="maintain">Maintain</option><option value="general">General</option><option value="custom">Custom</option></select></label><label>Calories<input name="target_calories_kcal" type="number" inputMode="numeric" /></label><label>Maintenance<input name="estimated_maintenance_kcal" type="number" inputMode="numeric" /></label></Form><p className="muted">{phases?.map(p => p.name).join(" · ") || "No phases yet"}</p></section><section className="section"><h2>Program</h2><Form kind="program"><label>Name<input name="name" required placeholder="PPL 2026" /></label><label>Start<input name="start_date" type="date" required defaultValue={today} /></label></Form><p className="muted">{programs?.map(p => p.name).join(" · ") || "No programs yet"}</p></section><section className="section"><h2>Exercise</h2><Form kind="exercise"><label>Name<input name="name" required placeholder="Barbell bench press" /></label></Form><p className="muted">{exercises?.map(e => e.name).join(" · ") || "No exercises yet"}</p></section><section className="section"><h2>Workout template</h2><Form kind="template"><label>Name<input name="name" required placeholder="Push A" /></label><label>Program<select name="program_id"><option value="">No program</option>{programs?.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></Form><p className="muted">{templates?.map(t => t.name).join(" · ") || "No templates yet"}</p></section><nav className="bottom-nav"><Link href="/">Today</Link><Link href="/train">Train</Link><Link href="/history">History</Link><Link href="/body">Body</Link><Link href="/setup">Setup</Link></nav></main>;
}
